# Generated by Django 4.2 on 2023-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vlog", "0002_comment_comment_vlog_commen_created_940227_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
